---
- name: Create Zookeeper install path
  file: state=directory path={{zookeeper_install_path}}

- name: Download Zookeeper
  get_url: url={{zookeeper_download_url}} dest={{zookeeper_archive}}

- name: Unpack Zookeeper archive
  unarchive: src={{zookeeper_archive}} dest={{zookeeper_install_path}} copy=no creates={{zookeeper_name}}

- name: Fix ownership
  file: state=directory path={{airavata_home}} owner=airavata group=airavata recurse=yes

- name: Set symlink for Zookeeper cfg file
  file: state=link path={{zookeeper_cfg}} src={{zookeeper_sample_cfg}}
  notify: start zookeeper

- name: Set up Zookeeper firewall rule
  lineinfile: dest=/etc/sysconfig/iptables state=present
              regexp="^-A INPUT -s {{hostvars[item]['ansible_default_ipv4']['address']}} -p tcp -m state --state NEW -m tcp --dport {{zookeeper_port}} -j ACCEPT$"
              line="-A INPUT -s {{hostvars[item]['ansible_default_ipv4']['address']}} -p tcp -m state --state NEW -m tcp --dport {{zookeeper_port}} -j ACCEPT"
              insertbefore="^-A INPUT -j REJECT .*$"
  with_items:
    - "{{groups['airavata']}}"
  notify: restart iptables
