---
- hosts: apiserver
  remote_user: root
  vars:
    airavata_server: api-server
  roles:
  - apiserver

- hosts: orchestrator
  remote_user: root
  vars:
    airavata_server: orchestrator-server
  roles:
  - orchestrator

- hosts: gfac
  remote_user: root
  vars:
    airavata_server: gfac-server
  roles:
  - gfac
