---
- hosts: all
  remote_user: root
  roles:
  - common

- hosts: dbserver
  remote_user: root
  roles:
  - db

- hosts: zookeeper
  remote_user: root
  roles:
  - zookeeper

- hosts: rabbitmq
  remote_user: root
  roles:
  - rabbitmq

- hosts: airavata
  remote_user: root
  roles:
  - airavata_common
