---
- name: restart iptables
  service: name=iptables state=restarted

- name: start rabbitmq
  environment:
    JAVA_HOME: "{{java_default}}"
  sudo: yes
  sudo_user: airavata
  command: "{{rabbitmq_home}}/sbin/rabbitmq-server -detached"
