---
- name: Set up GFAC firewall rule
  lineinfile: dest={{iptable_rule_file}} state=present
              regexp="^-A INPUT -s {{hostvars[item]['ansible_default_ipv4']['address']}} -p tcp -m state --state NEW -m tcp --dport {{gfac_server_port}} -j ACCEPT$"
              line="-A INPUT -s {{hostvars[item]['ansible_default_ipv4']['address']}} -p tcp -m state --state NEW -m tcp --dport {{gfac_server_port}} -j ACCEPT"
              insertbefore="^-A INPUT -j REJECT .*$"
  with_items:
    - "{{groups['orchestrator']}}"
  notify: 
    - restart iptables

- name: Start GFAC
  environment:
    JAVA_HOME: "{{java_default}}"
  sudo: yes
  sudo_user: airavata
  command: "{{airavata_server_home}}/bin/gfac-server.sh start"
